POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Moikka",
    "author": "Jouse",
    "url": "jouse/moikka",
    "likes": 8,
    "userId": "661fbc61f4f9fc24789db552"
}